# A minimal config.yaml that won't break your existing setup
title: "Stadtforschung"

menu:
  main:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "Projekt"
      url: "/pages/projekt/"
      weight: 2
    - name: "Fallbeispiel"
      url: "/pages/fallbeispiel/"
      weight: 3
    - name: Stadtforschung
      url: /pages/stadtforschung/
      weight: 4
    - name: Methoden
      url: /pages/methoden/
      weight: 5
    - name: Quiz
      url: /pages/quiz/
      weight: 6
